//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adalbertus.BudgetPlanner {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BudgetPlanner {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BudgetPlanner() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Adalbertus.BudgetPlanner.BudgetPlanner", typeof(BudgetPlanner).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP TABLE IF EXISTS [Dictionary];
        ///CREATE TABLE [Budget] (
        ///  [Key] VARCHAR(32) PRIMARY KEY, 
        ///  [Position] INT DEFAULT 0,
        ///  [Value] TEXT, 
        ///  [IsActive] INT DEFAULT 1);
        ///
        ///
        ///DROP TABLE IF EXISTS [Budget];
        ///CREATE TABLE [Budget] (
        ///  [Id] INTEGER PRIMARY KEY AUTOINCREMENT, 
        ///  [DateFrom] DATETIME, 
        ///  [DateTo] DATETIME);
        ///
        ///DROP TABLE IF EXISTS [BudgetPlan];
        ///CREATE TABLE [BudgetPlan] (
        ///  [Id]  INTEGER PRIMARY KEY AUTOINCREMENT,   
        ///  [BudgetId] INTEGER NOT NULL,
        ///  [CashFlowId] INTEGER NOT NULL,
        ///  [Val [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string db_schema {
            get {
                return ResourceManager.GetString("db_schema", resourceCulture);
            }
        }
    }
}
