//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adalbertus.BudgetPlanner.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Adalbertus.BudgetPlanner.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Configuration VALUES(&apos;DatabaseVersion&apos;,&apos;1&apos;,&apos;2&apos;,&apos;Wersja bazy danych&apos;);
        ///INSERT INTO Configuration VALUES(&apos;IsFirstRun&apos;,&apos;1&apos;,&apos;True&apos;,&apos;Czy jest to pierwsze uruchomienie aplikacji&apos;);
        ///INSERT INTO Configuration VALUES(&apos;AuthorEmail&apos;,&apos;1&apos;,&apos;budzet-domowy@@pietkiewicz.pl&apos;,&apos;Adres autora aplikacji&apos;);
        ///INSERT INTO Configuration VALUES(&apos;HomePage&apos;,&apos;1&apos;,&apos;http://budzet-domowy.pietkiewicz.pl/&apos;,&apos;Adres strony WWW aplikacji&apos;);
        ///INSERT INTO Configuration VALUES(&apos;HelpPage&apos;,&apos;1&apos;,&apos;http://budzet-domowy.pietkiewicz.pl/pomoc&apos;,&apos; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string db_init {
            get {
                return ResourceManager.GetString("db_init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP TABLE IF EXISTS [Configuration];
        ///CREATE TABLE [Configuration] (
        ///  [Key] VARCHAR(64) PRIMARY KEY, 
        ///  [IsActive] INTEGER(1) DEFAULT 1,
        ///  [Value] TEXT,
        ///  [Decription] TEXT
        ///);
        ///
        ///DROP TABLE IF EXISTS [Budget];
        ///CREATE TABLE [Budget] (
        ///  [Id] INTEGER PRIMARY KEY AUTOINCREMENT, 
        ///  [DateFrom] DATETIME, 
        ///  [DateTo] DATETIME,
        ///  [TransferedValue] NUMERIC);
        ///
        ///DROP TABLE IF EXISTS [BudgetPlan];
        ///CREATE TABLE [BudgetPlan] (
        ///  [Id]  INTEGER PRIMARY KEY AUTOINCREMENT,   
        ///  [BudgetId] INTEGER NOT NULL,
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string db_schema {
            get {
                return ResourceManager.GetString("db_schema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE [Configuration] SET [Value] = &apos;http://budzet-domowy.pietkiewicz.pl/pomoc&apos; WHERE [Key] = &apos;HelpPage&apos;;
        ///UPDATE [Configuration] SET [Value] = &apos;http://budzet-domowy.pietkiewicz.pl/online-update&apos; WHERE [Key] = &apos;UpdatePage&apos;;
        ///UPDATE [Configuration] SET [Value] = &apos;2&apos; WHERE [Key] = &apos;DatabaseVersion&apos;;
        ///
        ///ALTER TABLE [Saving] ADD COLUMN [StartingBalance] NUMERIC NOT NULL DEFAULT 0;.
        /// </summary>
        internal static string db_update_v002 {
            get {
                return ResourceManager.GetString("db_update_v002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP TABLE IF EXISTS [BudgetTemplateItem];
        ///CREATE TABLE [BudgetTemplateItem] (
        ///  [Id]  INTEGER PRIMARY KEY AUTOINCREMENT,   
        ///  [TemplateTypeName] VARCHAR(500),
        ///  [ForeignId] INTEGER,
        ///  [Value] NUMERIC,
        ///  [Description] VARCHAR(500),
        ///  [MonthDay] INTEGER,
        ///  [RepeatInterval] INTEGER, -- month unit - i.e. 1 - each month, 3 - each quarter
        ///  [IsActive] INTEGER(1) DEFAULT 1
        ///);
        ///
        ///DROP TABLE IF EXISTS [BudgetTemplateHistory];
        ///CREATE TABLE [BudgetTemplateHistory] (
        ///  [Id]  INTEGER PRIMARY KEY AUTOINCREME [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string db_update_v003 {
            get {
                return ResourceManager.GetString("db_update_v003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Budżet Domowy jest  własnością autora: Wojciech Pietkiewicz &lt;budzet-domowy@pietkiewicz.pl&gt;
        ///Strona WWW: budzet-domowy.pietkiewicz.pl
        ///            
        ///Program Budżet Domowy jest darmowy i może być użytkowany, kopiowany i przekazywany dalej, jeśli spełnione są następujące warunki: 
        ///1. Program może być używany prywatnie i zawodowo bez ograniczeń. Nie może być jednakże sprzedawany i nie może być dołączany do innych pakietów oprogramowania bez uzyskania zgody autora.
        ///2. Program może być umieszczany na be [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Licence {
            get {
                return ResourceManager.GetString("Licence", resourceCulture);
            }
        }
    }
}
