//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adalbertus.BudgetPlanner.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Adalbertus.BudgetPlanner.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Configuration VALUES(&apos;DatabaseVersion&apos;,&apos;1&apos;,&apos;2&apos;,&apos;Wersja bazy danych&apos;);
        ///INSERT INTO Configuration VALUES(&apos;IsFirstRun&apos;,&apos;1&apos;,&apos;True&apos;,&apos;Czy jest to pierwsze uruchomienie aplikacji&apos;);
        ///
        ///INSERT INTO CashFlowGroup VALUES(1,&apos;Dom&apos;,&apos;Wszystkie wydatki związane z domem&apos;,&apos;0&apos;,2);
        ///INSERT INTO CashFlowGroup VALUES(2,&apos;Oszczędności&apos;,NULL,&apos;1&apos;,11);
        ///INSERT INTO CashFlowGroup VALUES(3,&apos;Osobiste&apos;,&apos;Nasze ubrania, usługi, kosmetyki, kieszonkowe&apos;,&apos;0&apos;,3);
        ///INSERT INTO CashFlowGroup VALUES(4,&apos;Dzieci&apos;,&apos;Ubranka, pielęgnacja, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string db_init {
            get {
                return ResourceManager.GetString("db_init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP TABLE IF EXISTS [Configuration];
        ///CREATE TABLE [Configuration] (
        ///  [Key] VARCHAR(64) PRIMARY KEY, 
        ///  [IsActive] INTEGER(1) DEFAULT 1,
        ///  [Value] TEXT,
        ///  [Decription] TEXT
        ///);
        ///
        ///DROP TABLE IF EXISTS [Budget];
        ///CREATE TABLE [Budget] (
        ///  [Id] INTEGER PRIMARY KEY AUTOINCREMENT, 
        ///  [DateFrom] DATETIME, 
        ///  [DateTo] DATETIME,
        ///  [TransferedValue] NUMERIC);
        ///
        ///DROP TABLE IF EXISTS [BudgetPlan];
        ///CREATE TABLE [BudgetPlan] (
        ///  [Id]  INTEGER PRIMARY KEY AUTOINCREMENT,   
        ///  [BudgetId] INTEGER NOT NULL,
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string db_schema {
            get {
                return ResourceManager.GetString("db_schema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP TABLE IF EXISTS [BudgetCalculatorItem];
        ///CREATE TABLE [BudgetCalculatorItem] (
        ///  [Id]  INTEGER PRIMARY KEY AUTOINCREMENT,
        ///  [BudgetCalculatorEquationId] INTEGER NOT NULL,
        ///  [Name] VARCHAR(250),  
        ///  [ValueTypeName] VARCHAR(500),
        ///  [OperatorTypeName] VARCHAR(500),
        ///  [ForeignId] INTEGER,
        ///  [Value] NUMERIC,
        ///  [Text] VARCHAR(250),
        ///  [Position] INTEGER DEFAULT 0
        ///);
        ///
        ///DROP TABLE IF EXISTS [BudgetCalculatorEquation];
        ///CREATE TABLE [BudgetCalculatorEquation] (
        ///  [Id]  INTEGER PRIMARY KEY AUTOINCREME [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string db_update_v002 {
            get {
                return ResourceManager.GetString("db_update_v002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Domowy Budżet jest  własnością autora: Wojciech Pietkiewicz &lt;domowe-wydatki@pietkiewicz.pl&gt;
        ///            
        ///Program Domowy Budżet jest darmowy i może być użytkowany, kopiowany i przekazywany dalej, jeśli spełnione są następujące warunki: 
        ///1. Program może być używany prywatnie i zawodowo bez ograniczeń. Nie może być jednakże sprzedawany i nie może być dołączany do innych pakietów oprogramowania bez uzyskania zgody autora.
        ///2. Program może być umieszczany na bezpłatnych stronach interetowych do pobran [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Licence {
            get {
                return ResourceManager.GetString("Licence", resourceCulture);
            }
        }
    }
}
